ci: test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -35,7 +35,10 @@ jobs:
         run: exit 0
         continue-on-error: true
       - id: step2
-        run: exit 0
-        continue-on-error: true
-      - if: contains(steps.*.outcome, 'failure')
         run: exit 1
+        continue-on-error: true
+      - name: 'Fail this job if any step has failed'
+        if: contains(steps.*.outcome, 'failure')
+        run: |
+          echo "::error ::${{ toJson(steps) }}"
+          exit 1
